### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by LudovicRousseau**

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
The same problem is also present in many other files: no new line at end of file.

**Comment by cdesiles** [comment]
It is a harmless fix I accept, but why should there be end of file lines?

**Comment by LudovicRousseau** [comment]
Because when you use cat(1) to display a text file it is nice to have the shell prompt on a new line.
It is not a "end of file" but a new line.

**Comment by cdesiles** [comment]
Ok, I'm going to avoid that bad practice =)

**Comment by cdesiles** [comment]
Enhanced in [commit 28d4bd7](https://github.com/jokesterfr/node-pcsc/commit/9da9ec6ffc226c79c4b6f3d76fde1c42572c0eb8)

**Pull request merged**
